language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - export REPO_HOME="$TRAVIS_BUILD_DIR"
  - export PACKAGE_DIRS="$TRAVIS_BUILD_DIR/../"
  - chmod +x bin/install-meteor.sh
  - "bin/install-meteor.sh"

before_script:
  - "export PATH=$HOME/.meteor:$PATH"

cache:
  directories:
    - node_modules

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

services:
- mongodb

notifications:
  email: false
