language: node_js
node_js:
  - "4"
services:
  - mongodb
before_install:
  - export PATH="$HOME/.meteor:$PATH"
  - export REPO_HOME="$TRAVIS_BUILD_DIR"
  - export PACKAGE_DIRS="$TRAVIS_BUILD_DIR/../"
  - "bin/install-meteor.sh"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
